version: '3.8'

services:
  mockserver:
    image: mockserver/mockserver
    environment:
      - logLevel=INFO
    ports:
      - 1080:1080

  seeder:
    image: ${DOCKER_REGISTRY-}mockserver-seed:${TAG:-latest}
    build:
      context: .
      dockerfile: ./seed/Dockerfile
    depends_on:
      - mockserver